performing smoke test 07.5

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -361,12 +361,12 @@ jobs:
               --query 'Reservations[*].Instances[*].PublicIpAddress' \
               --output text)
             export API_URL="http://${BACKEND_IP}:3030"
-            echo "${API_URL}"
+            echo "${API_URL}/api/status"
             if curl "${API_URL}/api/status" | grep "ok"
             then
-                return 0
+              exit 0
             else
-                return 1
+              exit 1
             fi
       - run:
           name: Frontend smoke test.
@@ -375,10 +375,10 @@ jobs:
             echo ${URL}
             if curl -s ${URL} | grep "Welcome"
             then
-                # Change this to 0 after the job fails
-                return 1
+              # Change this to 0 after the job fails
+              exit 1
             else
-                return 1
+              exit 1
             fi
       # - destroy-environment:  # rollback on failure
       #     workflow-id: ${CIRCLE_WORKFLOW_ID:0:7}
